services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  ci-cd_test:
    container_name: ci-cd_test
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pg:
